FROM python:3.11.4-slim-buster as build

# set environment variables
ENV PATH=/root/.local/bin:$PATH

WORKDIR /app

# install dependencies
RUN pip install --user --upgrade --no-cache-dir pip==22.3.1 && \
    pip install --user --no-cache-dir pipenv==2022.10.25

# copy to a fresh image for reduced size
FROM python:3.11.4-slim-buster

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PATH=/root/.local/bin:$PATH

# copy project
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

WORKDIR /app/src

CMD ["pytest"]
