name: Build-And-Push

on:
  push:
    branches:
      - main

concurrency:
  group: ci-deployment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Build Docker Image
        env:
          IMAGE_REGISTRY: ${{ vars.IMAGE_REGISTRY }}
        run: make image-build IMAGE_TAG=${GITHUB_REF##*/}

      - name: Build Docker Image
        env:
          IMAGE_REGISTRY: ${{ vars.IMAGE_REGISTRY }}
        run: make image-test IMAGE_TAG=${GITHUB_REF##*/}

      - name: 'Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: 'Deploy'
        run: echo "${{steps.auth.outputs.credentials_file_path}}"
