name: gcr-cleaner

on:
  schedule:
    - cron: '0 0 */1 * *' # runs daily
  workflow_dispatch: # allows for manual invocation

jobs:
  gcr-cleaner:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Login to GAR
        uses: docker/login-action@v2
        with:
          username: _json_key
          password: ${{ secrets.GOOGLE_CREDENTIALS }}

      # customize based on the gcr-cleaner flags
      - name: clean-bot
        uses: 'docker://europe-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner'
        with:
          args: >-
            -repo=${{ secrets.GCP_ARTIFACT_REGISTRY }}/e2e
            -recursive
            -grace=1h
