name: gcr-cleaner

on:
  schedule:
    - cron: '0 0 */1 * *' # runs daily
  workflow_dispatch: # allows for manual invocation

jobs:
  gcr-cleaner:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 5
    steps:
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: 'Authenticate to Docker'
        run: |
          gcloud auth print-access-token | docker login \
          -u oauth2accesstoken \
          --password-stdin https://europe-central2-docker.pkg.dev

      - name: clean-bot
        uses: 'docker://europe-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli'
        with:
          args: >-
            -repo=${{ secrets.GCP_ARTIFACT_REGISTRY }}/bot/bot
            -grace=10m
            -tag-filter-any="main*"
            -keep=1

      - name: clean-e2e
        uses: 'docker://europe-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli'
        with:
          args: >-
            -repo=${{ secrets.GCP_ARTIFACT_REGISTRY }}/bot/e2e
            -grace=10m
            -tag-filter-any=".*"
